#ifndef HAVE_CONFIG_H
#define HAVE_CONFIG_H

/* generated by cmake, do not modify. modify config.h.cmake instead */

#define PACKAGE_NAME "${CMAKE_PROJECT_NAME}"
#define PACKAGE_VERSION "${Cello_VERSION_STRING}"

/* echo "#cmakedefine STDC_HEADERS" && grep HAVE_ cmake/configure.cmake | sed -e 's/.*\(HAVE_[A-Z_]*\).*/#cmakedefine \1/' */

#cmakedefine HAVE_STDINT_H
#cmakedefine STDC_HEADERS
#cmakedefine HAVE_STDBOOL_H
#cmakedefine HAVE_UNISTD_H

#cmakedefine HAVE_MEMMOVE
#cmakedefine HAVE_STRCHR
#cmakedefine HAVE_STRSTR
#cmakedefine HAVE_MALLOC
#cmakedefine HAVE_REALLOC

#cmakedefine HAVE_FLOOR
#cmakedefine HAVE_POW
#cmakedefine HAVE_SQRT

#endif
